name: red-tetris

services:
  react:
    container_name: react
    build:
      context: ./front
      dockerfile: Dockerfile
    image: react
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - ./front:/app
      - /app/node_modules
    networks:
      - main

  adonis:
    container_name: adonis
    build:
      context: ./back
      dockerfile: Dockerfile
    env_file:
      - .env
    image: adonis
    ports:
      - '3334:3334'
    volumes:
      - ./back:/app
      - /app/node_modules
    networks:
      - main

  postgres:
    image: postgres:16.1-alpine3.19
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - main

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - main

volumes:
  postgres:
    name: postgres-volume

networks:
  main:
