version: '3.8'
services:
  react:
    container_name: react
    build:
      context: ./front
      dockerfile: Dockerfile
    image: react
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - ./front:/front
      - /front/node_modules
    networks:
      - main

  # nest:
  #   container_name: nest
  #   build:
  #     context: ./back
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   image: nest
  #   ports:
  #     - '4000:4000'
  #   volumes:
  #     - ./back:/app
  #   networks:
  #     - main

networks:
  main: